# Generated by Django 5.2 on 2025-04-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('preco_diario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_imagem', models.ImageField(upload_to='categorias/imagens/')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
