# Generated by Django 5.2 on 2025-04-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='preco_diario',
        ),
    ]
