# Generated by Django 5.2 on 2025-04-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
